# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170504_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='student',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
