# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170507_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='视频时长(分钟数)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(default='www.baidu.com', verbose_name='访问地址'),
        ),
    ]
